services:
  db:
    image: postgres:16-alpine
    container_name: todo_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: talima
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d talima" ]
      interval: 3s
      timeout: 5s
      retries: 5

  fastapi-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: todo_fastapi_dev
    profiles: [ "dev" ]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  fastapi-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: todo_fastapi_prod
    profiles: [ "prod" ]
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
